# H2 http://localhost:8080/h2-console
# Only for Test Purpose
spring:
#  h2:
#    console:
#      enabled: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090