
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      #uri: mongodb://user:secret@localhost:27017
#      uri: mongodb://localhost:27017
      uri: mongodb://mongodb:27017
      database: cookma
  jackson:
      serialization:
        write-dates-as-timestamps: false

server:
  port: 8090

security:
  oauth2:
    client:
      client-id: cookma
      client-secret: secret
  user:
    name: cookma_admin
    password: pass01wd!
    role: ADMIN
